export interface TicketCountRowInterface {
	readonly ticket_type_id: string,
	readonly ticket_name: string,
	readonly ticket_stats: string,
	readonly event_id: string,
	readonly event_name: string,
	readonly organization_id: string,
	readonly allocation_count: number,
	readonly unpurchased_count: number,
	readonly available_count: number,
	readonly comp_count: number,
	readonly comp_available_count: number,
	readonly comp_redeemed_count: number,
	readonly comp_purchased_count: number,
	readonly comp_reserved_count: number,
	readonly comp_nullified_count: number,
	readonly hold_count: number,
	readonly hold_available_count: number,
	readonly hold_redeemed_count: number,
	readonly hold_purchased_count: number,
	readonly hold_reserved_count: number,
	readonly hold_nullified_count: number,
}

export interface TicketCountSalesRowInterface {
	readonly event_id: string,
	readonly organization_id: string,
	readonly ticket_type_id: string,
	readonly box_office_count: number,
	readonly online_count: number,
	readonly box_office_sales_in_cents: number,
	readonly online_sales_in_cents: number,
	readonly total_box_office_fees_in_cents: number,
	readonly total_online_fees_in_cents: number,
	readonly company_box_office_fees_in_cents: number,
	readonly client_box_office_fees_in_cents: number,
	readonly company_online_fees_in_cents: number,
	readonly client_online_fees_in_cents: number,
}